### ISSUE TITLE
Windows version stalls at initialization

### ISSUE THREAD

**Issue by gmaciocci** [codeforscience/sciencefair#59]
Windows version (on Windows 10 Creator's Update, x64) stalls at a grey screen with an animated square. Window title is 'initial'.

**Comment by blahah** [comment]
this *might* be the same issue as #58 with case-sensitive file-paths

I'll test on Windows tonight and check

**Comment by blahah** [comment]
Possibly fixed in beta4: https://github.com/codeforscience/sciencefair/releases/tag/v1.0.0-beta4 (downloads will appear when they have finished building)

**Comment by gmaciocci** [comment]
Still not loading beyond the 'initial' grey screen on Windows 10

**Comment by joehand** [comment]
@gmaciocci, I had similar issue and was able to resolve it by closing the app, removing the `~/.sciencefair` folder, and opening the app again.

**Comment by blahah** [comment]
OK I'll debug on a Windows machine this evening

**Comment by gmaciocci** [comment]
@joehand no luck on Windows 10.

**Comment by blahah** [comment]
OK I have identified a set of bugs that are Windows-specific:

- [ ] The `nanoraf` router that is used by `choo` can't resolve routes in electron+windows. Solution is to use hash routes instead of slash routes (e.g. `#home` instead of `/home`)
- [ ] The [discovery-swarm](https://github.com/mafintosh/discovery-swarm/blob/master/index.js#L14) module uses `utp-native` for UTP, but it's silently failing on windows10, and because we have TCP turned off we end up with no way to connect at all (rerpoted issue https://github.com/mafintosh/discovery-swarm/issues/27). Short term solution: turn on TCP and UTP. Long term solution: make UTP work on windows.
- [ ] The [append-tree]() module used by hyperdrive uses `/` as the path separator, which breaks on Win (reported issue https://github.com/mafintosh/append-tree/issues/7). Solution: fix append-tree so it uses `path.sep` which is OS-aware.

I need to fix the above before I can see if there are any more issues, as I can't progress to the point of having metadata synced right now.

**Comment by blahah** [comment]
@mafintosh preferred that the solution to the append-tree issue should be in hyperdrive, keeping append-tree abstract. So here's the PR for the fix: https://github.com/mafintosh/hyperdrive/pull/159

**Comment by blahah** [comment]
Found another windows quirk - CSS urls for local files don't work as normal, so node's usually cross platform path-joining breaks things.

**Comment by blahah** [comment]
v1.0.0-beta5 contains all the above fixes - I suspect there will be more Windows-specific issues but it was becoming impractical to find them without a new release.

Anyone with a Windows machine please feel free to try out this release and report issues in this thread.

**Comment by gmaciocci** [comment]
beta 5 appears to have broken the Mac release (Sierra 10.12.3):

* starting with a nuked .sciencefait folder allows the app to initialise to 99%. 
* App gets stuck synching initial data at 99%
* closing the app and restarting results in the app getting stuck at the grey screen with the animated squares.

**Comment by cboursnell** [comment]
Beta5 for windows now installs, opens, passes the square loading logo and then gets stuck at 0% of 'syncing initial data...'.
If you close it down and reopen it, it then gets stuck at the square loading logo, unless you delete the .sciencefair directory in home.

**Comment by blahah** [comment]
@cboursnell if you nuke the `~/.sciencefair` dir and run the app, is there any error in the console?

You can find the console in developer tools with: <kbd>Ctrl</kbd> <kbd>Shift</kbd> <kbd>I</kbd> or <kbd>F12</kbd>

**Comment by pkraker** [comment]
This is the error that I get on Win7:

    Uncaught ReferenceError: makesafe is not defined
    at module.exports.img (C:\Program Files\ScienceFair\resources\app\client\lib\imgpath.js:8)
    at CachedSearch._render (C:\Program Files\ScienceFair\resources\app\client\views\search.js:57)
    at CachedSearch.CacheElement.render (C:\Program Files\ScienceFair\resources\app\node_modules\cache-component\index.js:37)
    at module.exports (C:\Program Files\ScienceFair\resources\app\client\views\search.js:78)
    at module.exports (C:\Program Files\ScienceFair\resources\app\client\views\main.js:25)
    at module.exports (C:\Program Files\ScienceFair\resources\app\client\views\home.js:5)
    at C:\Program Files\ScienceFair\resources\app\node_modules\choo\index.js:43
    at emit (C:\Program Files\ScienceFair\resources\app\node_modules\nanorouter\index.js:47)
    at Function.<anonymous> (C:\Program Files\ScienceFair\resources\app\node_modules\choo\index.js:58)
    at redraw (C:\Program Files\ScienceFair\resources\app\node_modules\nanoraf\index.js:28)

**Comment by blahah** [comment]
thanks @pkraker, that was fixed in https://github.com/codeforscience/sciencefair/commit/5037dabcc2187512dd0f8dd28783b566a4bd9d62

release coming up after I finish some more bugfixes/enhancements

**Comment by blahah** [comment]
I think all the issues raised here have been solved by https://github.com/codeforscience/sciencefair/releases/tag/v1.0.0-beta9

As far as I can tell, [this issue](https://github.com/codeforscience/sciencefair/issues/71) is now the major/only Windows bug - if anyone can spare some energy to help debug it I would greatly appreciate it.

I'm closing this issue as the specific problems listed here has been solved. Thanks all for your help :)
